events {
  worker_connections  4096;
}

pid /tmp/nginx.pid;

http {

    include mime.types;

    server{
        listen 5173;
	listen [::]:5173;

        location / {
            root /app/;
            try_files $uri /index.html;
        }
    }
}